### PR TITLE
Redesign the UI for Stories List

### PR DESCRIPTION
**Pull request by swetasingh8844**
Add background color and modify the text size and also the color of each boxes changes when user will login again and again
image
image

### CODE REVIEW

**Comment by swetasingh8844** [comment]
I have done some changes. Please have a look.

**Comment by pooranjoyb** [comment]
> I have done some changes. Please have a look.

Please drop the Screenshots. :)

**Comment by swetasingh8844** [comment]
image

**Comment by pooranjoyb** [comment]
Nice Work Buddy! Just make the background a little more lighter :)

Use this `#AFDBF5` instead 🆗 
@swetasingh8844

**Comment by swetasingh8844** [comment]
image
is this fine?

**Comment by pooranjoyb** [comment]
Awesome work @swetasingh8844

**Pull request merged**
