### PR TITLE
Redesign the UI for Stories List 🚀 (Redesigned, added more functionalities and fix some errors)

### PR DESCRIPTION
**Pull request by AyushSinghbharti**
I have redesigned the Strories List screen.
In this new screen I have provided a functions as

1. Provide Logout and access account on Header
2. Provide facility to store and access their favoriate story
3. Can add story to favourite list easily
4. Use modal to show favourite list so that person can see favoriate list easily
5. use linear gradiant and blur method to provide good look (If needed we can reduce or change color set)

Overview of Stories List Screen are:

ss3
ss2
SS 1

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Hey @AyushSinghbharti 
The functionalities are really awesome. But please create issues before raising a PR. You are not allowed to directly raise a PR until you're assigned to work on an issue.
What I'll suggest is to create an issue for this PR and link this PR to it :)
Just don't wanna waste your precious contribution. Check the recent merged PR, it has the clean UI ready for the Stories list. You can then implement your functionalities on that UI. Make sure the Glassmorphism exists in the cards :)

Happy Coding 👍

**Comment by AyushSinghbharti** [comment]
Yup, about that I was little confused. when I was assigned with that issue #7 to me it was open so I started working on that issue but the time I had done it, it was close but might be because of some error #7 was still visible in issue section and any other pull request wasn't merged in master so I applied my pull request on this issue but It end up created conflict.

I'll take care of this from next time. Thanks.

**Comment by pooranjoyb** [comment]
Works! I've added `hard` label for this PR. Just raise a Issue for the same :)) @AyushSinghbharti

**Comment by AyushSinghbharti** [comment]
Sure @pooranjoyb, working on it.

**Comment by AyushSinghbharti** [comment]
I have updated all functionalities @pooranjoyb kindly review and tell me if any changes are required.

SS1
ss2
ss3

**Pull request merged**
